plugins {
    id 'java'
}

group = 'com.nttdata'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.9.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    // Dependencias
    implementation group: 'net.serenity-bdd', name: 'serenity-core', version: '3.6.23'
    implementation 'net.serenity-bdd:serenity-core:3.6.23'
    implementation group: 'net.serenity-bdd', name: 'serenity-junit', version: '3.6.23'
    testImplementation group: 'net.serenity-bdd', name: 'serenity-cucumber', version: '3.6.23'
    implementation group: 'net.serenity-bdd', name: 'serenity-screenplay-webdriver', version: '3.6.23'
    testImplementation group: 'junit', name: 'junit', version: '4.13.2'
    implementation group: 'net.serenity-bdd', name: 'serenity-screenplay', version: '3.6.23'
    implementation group: 'org.apache.maven.plugins', name: 'maven-compiler-plugin', version: '3.11.0'
    implementation group: 'net.serenity-bdd.maven.plugins', name: 'serenity-maven-plugin', version: '3.6.23'
    implementation group: 'net.serenity-bdd', name: 'serenity-ensure', version: '3.6.23'
    implementation group: 'io.github.bonigarcia', name: 'webdrivermanager', version: '5.6.3'
    implementation group: 'net.serenity-bdd', name: 'serenity-ensure', version: '3.6.23'
}

test {
    systemProperty "file.encoding", "utf-8"
}